name: GH Pages Deploy

on:
  push:
    branches: [master]
    paths-ignore:  # but the readme.md ?
      - "*.md"

  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"

jobs:
  build-deploy:
    name: Build and deploy app

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Get yarn cache
        id: yarn-cache
        run: echo "name=dir::$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: steps.yarn-cache.outputs.dir
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }} # TODO: Use yarn.lock instead, if that file exists in your repo.
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run-script build
